# Generated by Django 4.2.13 on 2025-04-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='emergencia_direccion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='emergencia_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='emergencia_parentesco',
            field=models.CharField(blank=True, max_length=50, verbose_name='Parentesco'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='emergencia_telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono de emergencia'),
        ),
    ]
