# Generated by Django 4.2.13 on 2024-07-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes_tolva',
            name='nombre_tolva',
            field=models.CharField(max_length=100, verbose_name='Nombre de Tolva'),
        ),
    ]
