# Generated by Django 4.2.13 on 2025-04-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitudes_tolva_nombre_tolva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes_epps',
            name='tipo_usuario',
            field=models.CharField(choices=[('Trabajador', 'Trabajador'), ('Jefe', 'Jefe'), ('Administrador Informático', 'Administrador Informático'), ('Administrador Operacional', 'Administrativo Operacional')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudes_retiro',
            name='tipo_usuario',
            field=models.CharField(choices=[('Trabajador', 'Trabajador'), ('Jefe', 'Jefe'), ('Administrador Informático', 'Administrador Informático'), ('Administrador Operacional', 'Administrativo Operacional')], max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudes_tolva',
            name='tipo_usuario',
            field=models.CharField(choices=[('Trabajador', 'Trabajador'), ('Jefe', 'Jefe'), ('Administrador Informático', 'Administrador Informático'), ('Administrador Operacional', 'Administrativo Operacional')], max_length=30),
        ),
    ]
